# Comment
language: node_js

node_js:
  - "6.9.4"

cache: npm

# Not required to install global dependency, e.g. angular-cli
install:
  - npm install

before_script:
  - cat ./patch/ng-cli/@angular/cli/models/webpack-configs/common.js
  - cp -rf ./patch/ng-cli/@angular/cli/models/webpack-configs/common.js ./node_modules/@angular/cli/models/webpack-configs/

script:
  - cat ./node_modules/@angular/cli/models/webpack-configs/common.js

addons:
  chrome: stable