# Comment
language: node_js

node_js:
  - "6.9.4"

cache: npm

# Not required to install global dependency, e.g. angular-cli
install:
  - npm install

before_script:
  - npm run patch-cli-ci-only

script:
  - ng test

addons:
  chrome: stable